---
- name: reload systemd
  become: True
  systemd:
    daemon_reload: yes

- name: restart alertmanager-bot
  become: True
  systemd:
    name: alertmanager-bot
    state: restarted
    enabled: yes
